# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # docker-compose.yml image tags (and any Dockerfiles at repo root)
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
